### PR TITLE
Dw/user auth

### PR DESCRIPTION
**Pull request by Alpine-lines**

### CODE REVIEW

**Comment by Alpine-lines** [comment]
build error caused by the following:

**Comment by Alpine-lines** [comment]
Build error caused by:

the .env file you gave me sets this as the alchemy key var

`NEXT_PUBLIC_MUMBAI="https://polygon-mumbai.g.alchemy.com/v2/4QdGUP8BOp3_NdNJAN1c2sWs12LtsfDF"
` 
then, i get this on fleek ci
```
 2022-05-09T19:22:45.048Z: Error: unsupported getDefaultProvider network (operation="getDefaultProvider", network="*****", code=NETWORK_ERROR, version=providers/5.6.5)
2022-05-09T19:22:45.048Z: at Logger.makeError (/workspace/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
2022-05-09T19:22:45.048Z: at Logger.throwError (/workspace/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
2022-05-09T19:22:45.048Z: at getDefaultProvider (/workspace/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/index.ts:70:16)
2022-05-09T19:22:45.048Z: at Object.8522 (/workspace/.next/server/pages/_app.js:2931:72)
2022-05-09T19:22:45.048Z: at __webpack_require__ (/workspace/.next/server/webpack-runtime.js:25:42)
2022-05-09T19:22:45.048Z: at __webpack_exec__ (/workspace/.next/server/pages/_app.js:3271:39)
2022-05-09T19:22:45.048Z: at /workspace/.next/server/pages/_app.js:3272:90
2022-05-09T19:22:45.048Z: at Function.__webpack_require__.X (/workspace/.next/server/webpack-runtime.js:190:21)
2022-05-09T19:22:45.048Z: at /workspace/.next/server/pages/_app.js:3272:47
2022-05-09T19:22:45.048Z: at Object.<anonymous> (/workspace/.next/server/pages/_app.js:3275:3)
2022-05-09T19:22:45.048Z: at Module._compile (node:internal/modules/cjs/loader:1095:14)
2022-05-09T19:22:45.048Z: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
2022-05-09T19:22:45.048Z: at Module.load (node:internal/modules/cjs/loader:975:32)
2022-05-09T19:22:45.048Z: at Function.Module._load (node:internal/modules/cjs/loader:816:12)
2022-05-09T19:22:45.048Z: at Module.require (node:internal/modules/cjs/loader:999:19)
2022-05-09T19:22:45.048Z: at require (node:internal/modules/cjs/helpers:93:18) {
2022-05-09T19:22:45.048Z: type: 'Error',
2022-05-09T19:22:45.048Z: reason: 'unsupported getDefaultProvider network',
2022-05-09T19:22:45.048Z: code: 'NETWORK_ERROR',
2022-05-09T19:22:45.048Z: operation: 'getDefaultProvider',
2022-05-09T19:22:45.048Z: network: '4QdGUP8BOp3_NdNJAN1c2sWs12LtsfDF'
2022-05-09T19:22:45.048Z: }
```
 
cause i was getting an error locally where it parsed the NEXT_PUBLIC_MUMBAI i showed there into this string
`https://polygon-mumbai.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_MUMBAI}`
so it should be made consistent across all .env versions and getDefaultProvider() in _app.tsx should just use either 
`process.env.NEXT_PUBLIC_MUMBAI
` or 
`https://polygon-mumbai.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_MUMBAI}`

**Comment by gawainb** [comment]
> Build error caused by:
> 
> the .env file you gave me sets this as the alchemy key var
> 
> `NEXT_PUBLIC_MUMBAI="https://polygon-mumbai.g.alchemy.com/v2/4QdGUP8BOp3_NdNJAN1c2sWs12LtsfDF" `
> 
> then, i get this on fleek ci
> 
> ```
> 2022-05-09T19:22:45.048Z: Error: unsupported getDefaultProvider network (operation="getDefaultProvider", network="*****", code=NETWORK_ERROR, version=providers/5.6.5)
> 2022-05-09T19:22:45.048Z: at Logger.makeError (/workspace/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
> 2022-05-09T19:22:45.048Z: at Logger.throwError (/workspace/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
> 2022-05-09T19:22:45.048Z: at getDefaultProvider (/workspace/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/index.ts:70:16)
> 2022-05-09T19:22:45.048Z: at Object.8522 (/workspace/.next/server/pages/_app.js:2931:72)
> 2022-05-09T19:22:45.048Z: at __webpack_require__ (/workspace/.next/server/webpack-runtime.js:25:42)
> 2022-05-09T19:22:45.048Z: at __webpack_exec__ (/workspace/.next/server/pages/_app.js:3271:39)
> 2022-05-09T19:22:45.048Z: at /workspace/.next/server/pages/_app.js:3272:90
> 2022-05-09T19:22:45.048Z: at Function.__webpack_require__.X (/workspace/.next/server/webpack-runtime.js:190:21)
> 2022-05-09T19:22:45.048Z: at /workspace/.next/server/pages/_app.js:3272:47
> 2022-05-09T19:22:45.048Z: at Object.<anonymous> (/workspace/.next/server/pages/_app.js:3275:3)
> 2022-05-09T19:22:45.048Z: at Module._compile (node:internal/modules/cjs/loader:1095:14)
> 2022-05-09T19:22:45.048Z: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
> 2022-05-09T19:22:45.048Z: at Module.load (node:internal/modules/cjs/loader:975:32)
> 2022-05-09T19:22:45.048Z: at Function.Module._load (node:internal/modules/cjs/loader:816:12)
> 2022-05-09T19:22:45.048Z: at Module.require (node:internal/modules/cjs/loader:999:19)
> 2022-05-09T19:22:45.048Z: at require (node:internal/modules/cjs/helpers:93:18) {
> 2022-05-09T19:22:45.048Z: type: 'Error',
> 2022-05-09T19:22:45.048Z: reason: 'unsupported getDefaultProvider network',
> 2022-05-09T19:22:45.048Z: code: 'NETWORK_ERROR',
> 2022-05-09T19:22:45.048Z: operation: 'getDefaultProvider',
> 2022-05-09T19:22:45.048Z: network: '4QdGUP8BOp3_NdNJAN1c2sWs12LtsfDF'
> 2022-05-09T19:22:45.048Z: }
> ```
> 
> cause i was getting an error locally where it parsed the NEXT_PUBLIC_MUMBAI i showed there into this string
> 
> `https://polygon-mumbai.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_MUMBAI}`
> 
> so it should be made consistent across all .env versions and getDefaultProvider() in _app.tsx should just use either
> 
> `process.env.NEXT_PUBLIC_MUMBAI `
> 
> or
> 
> `https://polygon-mumbai.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_MUMBAI}`

I'm cool with either way

**Comment by Alpine-lines** [comment]
kk, well i think the .env that fleek is using should model the one you provided me with such that

`NEXT_PUBLIC_MUMBAI="https://polygon-mumbai.g.alchemy.com/v2/4QdGUP8BOp3_NdNJAN1c2sWs12LtsfDF"`

and

**Review by gawainb — APPROVED** [review]

**Pull request merged**
